//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeReceipt
    {
        public int FeeReceiptId { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<short> FeeYear { get; set; }
        public Nullable<short> FeeMonth { get; set; }
        public Nullable<decimal> PreviousBalance { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
