//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class secPage
    {
        public int PageId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string Name { get; set; }
    }
}
